package config

const (
	// RootDir ...
	RootDir = "./rundoc/"
	// ConfigDir ...
	ConfigDir = "./rundoc/config/"
	// RunsDir ...
	RunsDir = "./rundoc/runs/"
	// DocsDir ...
	DocsDir = "./rundoc/docs/"
)
